/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCategoryDialog: typeof import('./src/components/admin/categories/AddCategoryDialog.vue')['default']
    BlogsList: typeof import('./src/components/blog/BlogsList.vue')['default']
    BlogsSection: typeof import('./src/components/admin/BlogsSection.vue')['default']
    CategoriesTable: typeof import('./src/components/admin/categories/CategoriesTable.vue')['default']
    CreateBlog: typeof import('./src/components/admin/CreateBlog.vue')['default']
    DialogClose: typeof import('radix-vue')['DialogClose']
    DialogContent: typeof import('radix-vue')['DialogContent']
    DialogDescription: typeof import('radix-vue')['DialogDescription']
    DialogOverlay: typeof import('radix-vue')['DialogOverlay']
    DialogPortal: typeof import('radix-vue')['DialogPortal']
    DialogRoot: typeof import('radix-vue')['DialogRoot']
    DialogTitle: typeof import('radix-vue')['DialogTitle']
    NavBar: typeof import('./src/components/navBar.vue')['default']
    RemoveBlogDialog: typeof import('./src/components/admin/RemoveBlogDialog.vue')['default']
    RemoveCategoryDialog: typeof import('./src/components/admin/categories/RemoveCategoryDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectViewport: typeof import('radix-vue')['SelectViewport']
    UpdateBlogDialog: typeof import('./src/components/admin/UpdateBlogDialog.vue')['default']
    UpdateCategoryDialog: typeof import('./src/components/admin/categories/UpdateCategoryDialog.vue')['default']
    UsersSection: typeof import('./src/components/admin/UsersSection.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
