/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCategoryDialog: typeof import('./src/components/admin/AddCategoryDialog.vue')['default']
    BlogsSection: typeof import('./src/components/admin/BlogsSection.vue')['default']
    CreateBlog: typeof import('./src/components/admin/CreateBlog.vue')['default']
    DialogClose: typeof import('radix-vue')['DialogClose']
    DialogContent: typeof import('radix-vue')['DialogContent']
    DialogDescription: typeof import('radix-vue')['DialogDescription']
    DialogOverlay: typeof import('radix-vue')['DialogOverlay']
    DialogPortal: typeof import('radix-vue')['DialogPortal']
    DialogRoot: typeof import('radix-vue')['DialogRoot']
    DialogTitle: typeof import('radix-vue')['DialogTitle']
    DialogTrigger: typeof import('radix-vue')['DialogTrigger']
    DropdownMenuContent: typeof import('radix-vue')['DropdownMenuContent']
    DropdownMenuItem: typeof import('radix-vue')['DropdownMenuItem']
    DropdownMenuPortal: typeof import('radix-vue')['DropdownMenuPortal']
    DropdownMenuRoot: typeof import('radix-vue')['DropdownMenuRoot']
    DropdownMenuTrigger: typeof import('radix-vue')['DropdownMenuTrigger']
    NavBar: typeof import('./src/components/navBar.vue')['default']
    PaginationEllipsis: typeof import('radix-vue')['PaginationEllipsis']
    PaginationFirst: typeof import('radix-vue')['PaginationFirst']
    PaginationLast: typeof import('radix-vue')['PaginationLast']
    PaginationList: typeof import('radix-vue')['PaginationList']
    PaginationListItem: typeof import('radix-vue')['PaginationListItem']
    PaginationNext: typeof import('radix-vue')['PaginationNext']
    PaginationPrev: typeof import('radix-vue')['PaginationPrev']
    PaginationRoot: typeof import('radix-vue')['PaginationRoot']
    RemoveBlogDialog: typeof import('./src/components/admin/RemoveBlogDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateBlogDialog: typeof import('./src/components/admin/UpdateBlogDialog.vue')['default']
    UsersSection: typeof import('./src/components/admin/UsersSection.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
